[build]
  base = "web/"
  command = "npm run build:app"
  publish = "public"
  environment = { NODE_VERSION = "16.13.2" }

[context.staging.environment]
  NODE_ENV = "development"

[context.preview.environment]
  NODE_ENV = "development"